### PR TITLE
Wrap returned errors

### LINKED ISSUE #56: Wrap all upstream errors with errors.Wrap
All upstream package errors should be wrapped with `errors.Wrap()` with an error message describing the error clause.

These errors should be propagated to caller, and eventually to the `main`, where they should be handled.

For example, take this block of code from `dispatcher.go`
```
if cancel {
		err := t.Cancel()
		if err != nil {
			d.log(fields).WithError(err).Error("failed to cancel task")
			return err
		}
}
```

and replace with,
```
if cancel {
		err := t.Cancel()
		if err != nil {
			d.log(fields).WithError(err).Error("failed to cancel task")
			return errors.Wrap(err, "failed to cancel task")
		}
}
```

This needs to be done across the package.

### PR DESCRIPTION
**Pull request by rentziass**
Fixes #56

Wrap errors in:
  - internal/dispatcher/dispatcher.go
  - internal/dispatcher/task.go
  - models/db.go
  - pkg/vegeta/options.go
  - pkg/vegeta/report.go
  - pkg/vegeta/vegeta.go
  - internal/reporter/reporter.go

### CODE REVIEW

File: internal/reporter/reporter.go [hunk 1]
```diff
@@ -4,6 +4,8 @@ import (
 	"bytes"
 	"vegeta-server/models"
 	"vegeta-server/pkg/vegeta"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/reporter/reporter.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: internal/dispatcher/dispatcher.go [hunk 2]
```diff
@@ -8,6 +8,7 @@ import (
 
 	"sync"
 	"vegeta-server/models"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/dispatcher/dispatcher.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: internal/dispatcher/task.go [hunk 3]
```diff
@@ -13,6 +13,7 @@ import (
 	"io"
 	"io/ioutil"
 	"vegeta-server/models"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/dispatcher/task.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: internal/reporter/reporter.go [hunk 4]
```diff
@@ -4,6 +4,8 @@ import (
...
+	"fmt"
```
Comment (golangcibot) [inline internal/reporter/reporter.go]: File is not `goimports`-ed (from `goimports`)

File: internal/reporter/reporter.go [hunk 5]
```diff
@@ -2,6 +2,8 @@ package reporter
 
 import (
 	"bytes"
+	"fmt"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/reporter/reporter.go]: File is not `goimports`-ed (from `goimports`)

File: internal/dispatcher/dispatcher.go [hunk 6]
```diff
@@ -6,6 +6,7 @@ import (
 
 	log "github.com/sirupsen/logrus"
 
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/dispatcher/dispatcher.go]: File is not `goimports`-ed (from `goimports`)

File: internal/dispatcher/task.go [hunk 7]
```diff
@@ -10,6 +10,7 @@ import (
 
 	log "github.com/sirupsen/logrus"
 
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline internal/dispatcher/task.go]: File is not `goimports`-ed (from `goimports`)

File: models/db.go [hunk 8]
```diff
@@ -2,6 +2,7 @@ package models
 
 import (
 	"fmt"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline models/db.go]: File is not `goimports`-ed (from `goimports`)

File: pkg/vegeta/options.go [hunk 9]
```diff
@@ -8,6 +8,8 @@ import (
 	"time"
 	"vegeta-server/models"
 
+	"fmt"
```
Comment (golangcibot) [inline pkg/vegeta/options.go]: File is not `goimports`-ed (from `goimports`)

File: internal/dispatcher/dispatcher.go [hunk 10]
```diff
@@ -149,15 +151,16 @@ func (d *dispatcher) Cancel(id string, cancel bool) error {
 	if !ok {
 		d.log(fields).Error("task not found")
 		d.mu.RUnlock()
-		return fmt.Errorf("cannot find task with id %s", id)
```
Comment (nitishm) [inline internal/dispatcher/dispatcher.go]: You can leave this as is. Otherwise it double wraps the same error.

File: internal/dispatcher/task.go [hunk 11]
```diff
@@ -103,7 +105,8 @@ func (t *task) Run(fn AttackFunc) error {
 	id := t.ID()
 
 	if status != models.AttackResponseStatusScheduled {
-		return fmt.Errorf("cannot run task %s with status %s", id, status)
```
Comment (nitishm) [inline internal/dispatcher/task.go]: Same as earlier.

File: internal/dispatcher/task.go [hunk 12]
```diff
@@ -125,12 +128,13 @@ func (t *task) Complete(result io.Reader) error {
 	id := t.ID()
 
 	if status != models.AttackResponseStatusRunning {
-		return fmt.Errorf("cannot mark completed for task %s with status %s", id, status)
```
Comment (nitishm) [inline internal/dispatcher/task.go]: Ditto

**Comment by nitishm** [comment]
Looks like you got everything. Just need the minor fixes and then it's good to merge. Great job @rentziass

File: models/db.go [hunk 13]
```diff
@@ -3,6 +3,8 @@ package models
 import (
 	"fmt"
 	"sync"
+
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline models/db.go]: "vegeta-server/vendor/github.com/pkg/errors" imported but not used (from `typecheck`)

File: models/db.go [hunk 14]
```diff
@@ -3,6 +3,8 @@ package models
 import (
 	"fmt"
 	"sync"
+
```
Comment (golangcibot) [inline models/db.go]: File is not `goimports`-ed (from `goimports`)
